# Dockerfile for the frontend.

FROM golang:latest as build
WORKDIR /app 
ADD . . 
RUN go build -o main . 

FROM iron/go
COPY --from=build /app/main /app/
COPY views/ /app/views
EXPOSE 8080:8080
RUN ls /app/views/js
ENTRYPOINT ["/app/main"]
