kind: pipeline
name: default

platform:
  arch: amd64
  os: linux

steps:
    - name: test
      image: golang:1.14
      commands:
          - cd sherlockcrawler/sherlockcrawler
          - go test
          - cd ..
          - go build -o sherlockcrawlermain
          - cd ../analyser/sherlockanalyser
          - go test
          - cd ../sherlockparser
          - go test
          - cd ..
          - go build -o analysermain
          - cd ../frontend
          - go build -o frontendmain
          - cd ../sherlockneo
          - go test
          - cd ../webserver/webserver
          - go test
          - cd ..
          - go build -o webservermain
    - name: lint
      image: golangci/golangci-lint
      commands:
          - golangci-lint run
