kind: pipeline
name: default

platform:
  arch: amd64
  os: linux

steps:
    - name: test
      image: golang:1.14
      commands:
          - apt install pkg-config
          - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-18.04.deb
          - apt intall-get ./seabolt-1.7.4-Linux-ubuntu-18.04.deb
          - go get github.com/neo4j/neo4j-go-driver/neo4j
          - go test
          - go build
    - name: lint
      image: golangci/golangci-lint
      commands:
          - golangci-lint run
