kind: pipeline
name: default

steps:
    - name: test
      image: golang
      commands:
          - go test
          - go build
    - name: lint
      image: golangci/golangci-lint
      commands:
          - golangci-lint run
