kind: pipeline
name: default

platform:
  arch: amd64
  os: linux

steps:
    - name:
      image: golang:1.14
      commands:
          - neo4j start
          - sleep 5
          - go test
          - go build
    - name: lint
      image: golangci/golangci-lint
      commands:
          - golangci-lint run
