FROM golang:1.14 as build
COPY . /app
WORKDIR /app
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o dockcrawler ./sherlockcrawler

FROM alpine:latest
COPY --from=build /app/dockcrawler /app/
EXPOSE 8200
ENTRYPOINT ["/app/dockcrawler"]
