# Dockerfile crawler

FROM golang:1.14 as build
COPY . /app
WORKDIR /app

RUN ls -la
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o dockcrawler .

FROM alpine:latest
COPY --from=build /app/dockcrawler /app/
EXPOSE 8200
RUN ls -la /app
ENTRYPOINT ["/app/dockcrawler"]