// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawlerproto.proto

package crawlerwebserverproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Status of the Crawler.
type ServiceStatus int32

const (
	ServiceStatus_DONE ServiceStatus = 0
)

var ServiceStatus_name = map[int32]string{
	0: "DONE",
}

var ServiceStatus_value = map[string]int32{
	"DONE": 0,
}

func (x ServiceStatus) String() string {
	return proto.EnumName(ServiceStatus_name, int32(x))
}

func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{0}
}

//
//State of the url. Like can be crawled or is rejected.
type URL_STATUS int32

const (
	URL_STATUS_ok      URL_STATUS = 0
	URL_STATUS_failure URL_STATUS = 1
)

var URL_STATUS_name = map[int32]string{
	0: "ok",
	1: "failure",
}

var URL_STATUS_value = map[string]int32{
	"ok":      0,
	"failure": 1,
}

func (x URL_STATUS) String() string {
	return proto.EnumName(URL_STATUS_name, int32(x))
}

func (URL_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{1}
}

//
//CurrentState represents the state that the analyser will transfer to.
type CurrentState int32

const (
	CurrentState_Stop    CurrentState = 0
	CurrentState_Pause   CurrentState = 1
	CurrentState_Running CurrentState = 2
	CurrentState_Clean   CurrentState = 3
)

var CurrentState_name = map[int32]string{
	0: "Stop",
	1: "Pause",
	2: "Running",
	3: "Clean",
}

var CurrentState_value = map[string]int32{
	"Stop":    0,
	"Pause":   1,
	"Running": 2,
	"Clean":   3,
}

func (x CurrentState) String() string {
	return proto.EnumName(CurrentState_name, int32(x))
}

func (CurrentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{2}
}

//
//CrawlTaskCreateRequest will be the request for the url.
type CrawlTaskCreateRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlTaskCreateRequest) Reset()         { *m = CrawlTaskCreateRequest{} }
func (m *CrawlTaskCreateRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlTaskCreateRequest) ProtoMessage()    {}
func (*CrawlTaskCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{0}
}

func (m *CrawlTaskCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlTaskCreateRequest.Unmarshal(m, b)
}
func (m *CrawlTaskCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlTaskCreateRequest.Marshal(b, m, deterministic)
}
func (m *CrawlTaskCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlTaskCreateRequest.Merge(m, src)
}
func (m *CrawlTaskCreateRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlTaskCreateRequest.Size(m)
}
func (m *CrawlTaskCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlTaskCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlTaskCreateRequest proto.InternalMessageInfo

func (m *CrawlTaskCreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

//
//CrawlTaskCreateResponse will be the response telling the state of the requested url.
type CrawlTaskCreateResponse struct {
	Statuscode           URL_STATUS `protobuf:"varint,1,opt,name=statuscode,proto3,enum=crawlerwebserverproto.URL_STATUS" json:"statuscode,omitempty"`
	Taskid               uint64     `protobuf:"varint,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CrawlTaskCreateResponse) Reset()         { *m = CrawlTaskCreateResponse{} }
func (m *CrawlTaskCreateResponse) String() string { return proto.CompactTextString(m) }
func (*CrawlTaskCreateResponse) ProtoMessage()    {}
func (*CrawlTaskCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{1}
}

func (m *CrawlTaskCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlTaskCreateResponse.Unmarshal(m, b)
}
func (m *CrawlTaskCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlTaskCreateResponse.Marshal(b, m, deterministic)
}
func (m *CrawlTaskCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlTaskCreateResponse.Merge(m, src)
}
func (m *CrawlTaskCreateResponse) XXX_Size() int {
	return xxx_messageInfo_CrawlTaskCreateResponse.Size(m)
}
func (m *CrawlTaskCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlTaskCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlTaskCreateResponse proto.InternalMessageInfo

func (m *CrawlTaskCreateResponse) GetStatuscode() URL_STATUS {
	if m != nil {
		return m.Statuscode
	}
	return URL_STATUS_ok
}

func (m *CrawlTaskCreateResponse) GetTaskid() uint64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

//
//TaskStatusRequest will represent a request for the current status of the tasks.
type TaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusRequest) Reset()         { *m = TaskStatusRequest{} }
func (m *TaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*TaskStatusRequest) ProtoMessage()    {}
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{2}
}

func (m *TaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusRequest.Unmarshal(m, b)
}
func (m *TaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *TaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusRequest.Merge(m, src)
}
func (m *TaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_TaskStatusRequest.Size(m)
}
func (m *TaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusRequest proto.InternalMessageInfo

//
//TaskStatusResponse will represent a response for a TaskStatusRequest.
type TaskStatusResponse struct {
	Website              string   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Undone               uint64   `protobuf:"varint,2,opt,name=undone,proto3" json:"undone,omitempty"`
	Processing           uint64   `protobuf:"varint,3,opt,name=processing,proto3" json:"processing,omitempty"`
	Finished             uint64   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Failed               uint64   `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusResponse) Reset()         { *m = TaskStatusResponse{} }
func (m *TaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatusResponse) ProtoMessage()    {}
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{3}
}

func (m *TaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusResponse.Unmarshal(m, b)
}
func (m *TaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *TaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusResponse.Merge(m, src)
}
func (m *TaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatusResponse.Size(m)
}
func (m *TaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusResponse proto.InternalMessageInfo

func (m *TaskStatusResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *TaskStatusResponse) GetUndone() uint64 {
	if m != nil {
		return m.Undone
	}
	return 0
}

func (m *TaskStatusResponse) GetProcessing() uint64 {
	if m != nil {
		return m.Processing
	}
	return 0
}

func (m *TaskStatusResponse) GetFinished() uint64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func (m *TaskStatusResponse) GetFailed() uint64 {
	if m != nil {
		return m.Failed
	}
	return 0
}

//
//SubmitURLRequest will submit a URL.
type SubmitURLRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,json=uRL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLRequest) Reset()         { *m = SubmitURLRequest{} }
func (m *SubmitURLRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitURLRequest) ProtoMessage()    {}
func (*SubmitURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{4}
}

func (m *SubmitURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLRequest.Unmarshal(m, b)
}
func (m *SubmitURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLRequest.Marshal(b, m, deterministic)
}
func (m *SubmitURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLRequest.Merge(m, src)
}
func (m *SubmitURLRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitURLRequest.Size(m)
}
func (m *SubmitURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLRequest proto.InternalMessageInfo

func (m *SubmitURLRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

//
//SubmitURLResponse will answer a SubmitURLRequest with a bool to indecate the status of the request.
type SubmitURLResponse struct {
	Recieved             bool     `protobuf:"varint,1,opt,name=recieved,proto3" json:"recieved,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLResponse) Reset()         { *m = SubmitURLResponse{} }
func (m *SubmitURLResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitURLResponse) ProtoMessage()    {}
func (*SubmitURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{5}
}

func (m *SubmitURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLResponse.Unmarshal(m, b)
}
func (m *SubmitURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLResponse.Marshal(b, m, deterministic)
}
func (m *SubmitURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLResponse.Merge(m, src)
}
func (m *SubmitURLResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitURLResponse.Size(m)
}
func (m *SubmitURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLResponse proto.InternalMessageInfo

func (m *SubmitURLResponse) GetRecieved() bool {
	if m != nil {
		return m.Recieved
	}
	return false
}

func (m *SubmitURLResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//
//StateRequest contains the CurrentState. future state of the analyser
type StateRequest struct {
	State                CurrentState `protobuf:"varint,1,opt,name=State,json=state,proto3,enum=crawlerwebserverproto.CurrentState" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StateRequest) Reset()         { *m = StateRequest{} }
func (m *StateRequest) String() string { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()    {}
func (*StateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{6}
}

func (m *StateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateRequest.Unmarshal(m, b)
}
func (m *StateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateRequest.Marshal(b, m, deterministic)
}
func (m *StateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateRequest.Merge(m, src)
}
func (m *StateRequest) XXX_Size() int {
	return xxx_messageInfo_StateRequest.Size(m)
}
func (m *StateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateRequest proto.InternalMessageInfo

func (m *StateRequest) GetState() CurrentState {
	if m != nil {
		return m.State
	}
	return CurrentState_Stop
}

//
//StateResponse that will be sent to the webserver. true if everything was successful.
type StateResponse struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateResponse) Reset()         { *m = StateResponse{} }
func (m *StateResponse) String() string { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()    {}
func (*StateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{7}
}

func (m *StateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateResponse.Unmarshal(m, b)
}
func (m *StateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateResponse.Marshal(b, m, deterministic)
}
func (m *StateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateResponse.Merge(m, src)
}
func (m *StateResponse) XXX_Size() int {
	return xxx_messageInfo_StateResponse.Size(m)
}
func (m *StateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateResponse proto.InternalMessageInfo

func (m *StateResponse) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

//
//StateGetRequest that will be sent to the crawler to get the current status of the crawler.
type StateGetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateGetRequest) Reset()         { *m = StateGetRequest{} }
func (m *StateGetRequest) String() string { return proto.CompactTextString(m) }
func (*StateGetRequest) ProtoMessage()    {}
func (*StateGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{8}
}

func (m *StateGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateGetRequest.Unmarshal(m, b)
}
func (m *StateGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateGetRequest.Marshal(b, m, deterministic)
}
func (m *StateGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateGetRequest.Merge(m, src)
}
func (m *StateGetRequest) XXX_Size() int {
	return xxx_messageInfo_StateGetRequest.Size(m)
}
func (m *StateGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateGetRequest proto.InternalMessageInfo

//
//StateGetResponse contains the CurrentState. current state of the crawler.
type StateGetResponse struct {
	State                CurrentState `protobuf:"varint,1,opt,name=State,json=state,proto3,enum=crawlerwebserverproto.CurrentState" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StateGetResponse) Reset()         { *m = StateGetResponse{} }
func (m *StateGetResponse) String() string { return proto.CompactTextString(m) }
func (*StateGetResponse) ProtoMessage()    {}
func (*StateGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a02d74997e28ce1, []int{9}
}

func (m *StateGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateGetResponse.Unmarshal(m, b)
}
func (m *StateGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateGetResponse.Marshal(b, m, deterministic)
}
func (m *StateGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateGetResponse.Merge(m, src)
}
func (m *StateGetResponse) XXX_Size() int {
	return xxx_messageInfo_StateGetResponse.Size(m)
}
func (m *StateGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateGetResponse proto.InternalMessageInfo

func (m *StateGetResponse) GetState() CurrentState {
	if m != nil {
		return m.State
	}
	return CurrentState_Stop
}

func init() {
	proto.RegisterEnum("crawlerwebserverproto.ServiceStatus", ServiceStatus_name, ServiceStatus_value)
	proto.RegisterEnum("crawlerwebserverproto.URL_STATUS", URL_STATUS_name, URL_STATUS_value)
	proto.RegisterEnum("crawlerwebserverproto.CurrentState", CurrentState_name, CurrentState_value)
	proto.RegisterType((*CrawlTaskCreateRequest)(nil), "crawlerwebserverproto.CrawlTaskCreateRequest")
	proto.RegisterType((*CrawlTaskCreateResponse)(nil), "crawlerwebserverproto.CrawlTaskCreateResponse")
	proto.RegisterType((*TaskStatusRequest)(nil), "crawlerwebserverproto.TaskStatusRequest")
	proto.RegisterType((*TaskStatusResponse)(nil), "crawlerwebserverproto.TaskStatusResponse")
	proto.RegisterType((*SubmitURLRequest)(nil), "crawlerwebserverproto.SubmitURLRequest")
	proto.RegisterType((*SubmitURLResponse)(nil), "crawlerwebserverproto.SubmitURLResponse")
	proto.RegisterType((*StateRequest)(nil), "crawlerwebserverproto.StateRequest")
	proto.RegisterType((*StateResponse)(nil), "crawlerwebserverproto.StateResponse")
	proto.RegisterType((*StateGetRequest)(nil), "crawlerwebserverproto.StateGetRequest")
	proto.RegisterType((*StateGetResponse)(nil), "crawlerwebserverproto.StateGetResponse")
}

func init() {
	proto.RegisterFile("crawlerproto.proto", fileDescriptor_2a02d74997e28ce1)
}

var fileDescriptor_2a02d74997e28ce1 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0x5b, 0x4f, 0x13, 0x5d,
	0x14, 0xed, 0xfd, 0xb2, 0x3f, 0x3e, 0x9d, 0x1e, 0x15, 0xeb, 0x3c, 0x18, 0x19, 0x89, 0x60, 0x8d,
	0x7d, 0xc0, 0x27, 0xe3, 0x13, 0xa9, 0x84, 0x98, 0xa0, 0xe8, 0x99, 0x12, 0x9f, 0x8c, 0x99, 0xb6,
	0xbb, 0x7a, 0xa4, 0xcc, 0xd4, 0x73, 0x81, 0xff, 0xe2, 0x9f, 0xd5, 0x73, 0xeb, 0x30, 0x08, 0x03,
	0xc4, 0x17, 0xc2, 0x3a, 0x7b, 0xed, 0xb5, 0x2f, 0x6b, 0x77, 0x80, 0x4c, 0x79, 0x72, 0xb6, 0x40,
	0xbe, 0xe4, 0x99, 0xcc, 0x86, 0xf6, 0x2f, 0x79, 0xe0, 0xdf, 0xce, 0x70, 0x22, 0x90, 0x9f, 0xfa,
	0x60, 0x34, 0x80, 0xf5, 0x91, 0x09, 0x8c, 0x13, 0x71, 0x3c, 0xe2, 0x98, 0x48, 0xa4, 0xf8, 0x53,
	0xa1, 0x90, 0x24, 0x80, 0xba, 0xe2, 0x8b, 0x7e, 0xf5, 0x49, 0x75, 0xbb, 0x4b, 0xcd, 0xbf, 0x91,
	0x84, 0x87, 0x97, 0xb8, 0x62, 0x99, 0xa5, 0x02, 0xc9, 0x2e, 0x80, 0x90, 0x89, 0x54, 0x62, 0x9a,
	0xcd, 0xd0, 0xe6, 0xdc, 0xd9, 0xd9, 0x18, 0x5e, 0x59, 0x72, 0x78, 0x44, 0x0f, 0xbe, 0xc6, 0xe3,
	0xdd, 0xf1, 0x51, 0x4c, 0x0b, 0x49, 0x64, 0x1d, 0x5a, 0x52, 0x0b, 0xb3, 0x59, 0xbf, 0xa6, 0xd3,
	0x1b, 0xd4, 0xa3, 0xe8, 0x1e, 0xf4, 0x4c, 0xc1, 0xd8, 0x32, 0x7d, 0x73, 0xd1, 0xaf, 0x2a, 0x90,
	0xe2, 0xab, 0x6f, 0xa3, 0x0f, 0x6d, 0x53, 0x8c, 0x49, 0xf4, 0x7d, 0xaf, 0xa0, 0x51, 0x57, 0xe9,
	0x2c, 0x4b, 0x71, 0xa5, 0xee, 0x10, 0x79, 0x0c, 0xa0, 0xbb, 0x9a, 0xa2, 0x10, 0x2c, 0xfd, 0xd6,
	0xaf, 0xdb, 0x58, 0xe1, 0x85, 0x84, 0xd0, 0x99, 0xb3, 0x94, 0x89, 0xef, 0x38, 0xeb, 0x37, 0x6c,
	0x34, 0xc7, 0x46, 0x73, 0x9e, 0xb0, 0x85, 0x8e, 0x34, 0x9d, 0xa6, 0x43, 0xd1, 0x26, 0x04, 0xb1,
	0x9a, 0x9c, 0x30, 0xa9, 0x27, 0x2d, 0x6c, 0x53, 0xa3, 0x7c, 0x9b, 0xf4, 0x20, 0xda, 0x83, 0x5e,
	0x81, 0xe5, 0x07, 0xd0, 0xe5, 0x38, 0x4e, 0x19, 0x9e, 0x6a, 0x51, 0xc3, 0xed, 0xd0, 0x1c, 0x93,
	0xfb, 0xd0, 0x44, 0xce, 0x33, 0x6e, 0x27, 0xe8, 0x52, 0x07, 0xa2, 0x77, 0xb0, 0x66, 0x96, 0x90,
	0xdb, 0xf6, 0x1a, 0x9a, 0x16, 0x7b, 0x13, 0x9e, 0x96, 0x98, 0x30, 0x52, 0x9c, 0x63, 0x2a, 0x5d,
	0x6a, 0xd3, 0xd8, 0x80, 0xd1, 0x0b, 0xf8, 0xdf, 0x4b, 0x5d, 0xe8, 0x06, 0xd9, 0xc5, 0x6e, 0x2c,
	0x8e, 0x7a, 0x70, 0xd7, 0x92, 0xf7, 0x51, 0xae, 0x4c, 0x79, 0xaf, 0xe7, 0xce, 0x9f, 0xbc, 0xc4,
	0xbf, 0xb7, 0x33, 0x78, 0xa4, 0xdb, 0xd1, 0x14, 0x36, 0x45, 0xe7, 0x32, 0xe9, 0x40, 0xe3, 0xed,
	0xe1, 0x87, 0xbd, 0xa0, 0x32, 0xd8, 0x00, 0x38, 0xbf, 0x22, 0xd2, 0x82, 0x5a, 0x76, 0x1c, 0x54,
	0xc8, 0x7f, 0xd0, 0x36, 0x0e, 0x28, 0x8e, 0x41, 0x75, 0xf0, 0x06, 0xd6, 0x8a, 0xa2, 0x26, 0x39,
	0x96, 0xd9, 0x52, 0xd3, 0xba, 0xd0, 0xfc, 0x98, 0x28, 0xa1, 0x49, 0x26, 0x83, 0xaa, 0x34, 0xd5,
	0x46, 0x07, 0x35, 0xf3, 0x3e, 0x5a, 0x60, 0x92, 0x06, 0xf5, 0x9d, 0xdf, 0x75, 0x68, 0x8f, 0x5c,
	0xa3, 0x24, 0x01, 0xa0, 0x6e, 0x68, 0x5d, 0x92, 0x6c, 0x95, 0x0c, 0xf0, 0xb7, 0xe1, 0xe1, 0xf6,
	0xcd, 0x44, 0xb7, 0xa2, 0xa8, 0x42, 0x7e, 0xe8, 0x53, 0xb0, 0x23, 0x1e, 0xce, 0xcd, 0x51, 0x7f,
	0x52, 0xa8, 0x90, 0x94, 0x09, 0x5c, 0xfa, 0x31, 0x84, 0xcf, 0x6f, 0xc1, 0xcc, 0x6b, 0x7d, 0x86,
	0x4e, 0x8c, 0x7e, 0x27, 0x65, 0x6e, 0x14, 0x0f, 0x2a, 0xdc, 0xbc, 0x9e, 0x94, 0x0b, 0x7f, 0x81,
	0xce, 0xfe, 0x4a, 0xf8, 0xd9, 0x75, 0x39, 0xe7, 0x17, 0x13, 0x6e, 0xdd, 0xc8, 0xcb, 0xe5, 0x4f,
	0x00, 0xdc, 0x37, 0xc7, 0x4c, 0x45, 0x5e, 0x96, 0xdd, 0xd1, 0x95, 0xdf, 0xb2, 0x70, 0x78, 0x5b,
	0xfa, 0xaa, 0xdc, 0xa4, 0x65, 0x09, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x8f, 0x38,
	0x0c, 0x4b, 0x05, 0x00, 0x00,
}
