FROM golang:1.14 as build
COPY . /app
WORKDIR /app
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o dockscreenshot ./screenshot

FROM alpine:latest
COPY --from=build /app/dockscreenshot /app/
RUN apk add chromium
EXPOSE 8202
ENTRYPOINT ["/app/dockscreenshot"]
