// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawlerToAnalyser.proto

package analyserinterface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type URL_STATUS int32

const (
	URL_STATUS_ok      URL_STATUS = 0
	URL_STATUS_failure URL_STATUS = 1
)

var URL_STATUS_name = map[int32]string{
	0: "ok",
	1: "failure",
}

var URL_STATUS_value = map[string]int32{
	"ok":      0,
	"failure": 1,
}

func (x URL_STATUS) String() string {
	return proto.EnumName(URL_STATUS_name, int32(x))
}

func (URL_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17c4b44578c50216, []int{0}
}

type CrawlTaskCreateRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlTaskCreateRequest) Reset()         { *m = CrawlTaskCreateRequest{} }
func (m *CrawlTaskCreateRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlTaskCreateRequest) ProtoMessage()    {}
func (*CrawlTaskCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17c4b44578c50216, []int{0}
}

func (m *CrawlTaskCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlTaskCreateRequest.Unmarshal(m, b)
}
func (m *CrawlTaskCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlTaskCreateRequest.Marshal(b, m, deterministic)
}
func (m *CrawlTaskCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlTaskCreateRequest.Merge(m, src)
}
func (m *CrawlTaskCreateRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlTaskCreateRequest.Size(m)
}
func (m *CrawlTaskCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlTaskCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlTaskCreateRequest proto.InternalMessageInfo

func (m *CrawlTaskCreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CrawlTaskCreateResponse struct {
	Statuscode           URL_STATUS `protobuf:"varint,1,opt,name=statuscode,proto3,enum=analyserinterface.URL_STATUS" json:"statuscode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CrawlTaskCreateResponse) Reset()         { *m = CrawlTaskCreateResponse{} }
func (m *CrawlTaskCreateResponse) String() string { return proto.CompactTextString(m) }
func (*CrawlTaskCreateResponse) ProtoMessage()    {}
func (*CrawlTaskCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17c4b44578c50216, []int{1}
}

func (m *CrawlTaskCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlTaskCreateResponse.Unmarshal(m, b)
}
func (m *CrawlTaskCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlTaskCreateResponse.Marshal(b, m, deterministic)
}
func (m *CrawlTaskCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlTaskCreateResponse.Merge(m, src)
}
func (m *CrawlTaskCreateResponse) XXX_Size() int {
	return xxx_messageInfo_CrawlTaskCreateResponse.Size(m)
}
func (m *CrawlTaskCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlTaskCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlTaskCreateResponse proto.InternalMessageInfo

func (m *CrawlTaskCreateResponse) GetStatuscode() URL_STATUS {
	if m != nil {
		return m.Statuscode
	}
	return URL_STATUS_ok
}

func init() {
	proto.RegisterEnum("analyserinterface.URL_STATUS", URL_STATUS_name, URL_STATUS_value)
	proto.RegisterType((*CrawlTaskCreateRequest)(nil), "analyserinterface.CrawlTaskCreateRequest")
	proto.RegisterType((*CrawlTaskCreateResponse)(nil), "analyserinterface.CrawlTaskCreateResponse")
}

func init() {
	proto.RegisterFile("crawlerToAnalyser.proto", fileDescriptor_17c4b44578c50216)
}

var fileDescriptor_17c4b44578c50216 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2e, 0x4a, 0x2c,
	0xcf, 0x49, 0x2d, 0x0a, 0xc9, 0x77, 0xcc, 0x4b, 0xcc, 0xa9, 0x2c, 0x4e, 0x2d, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0x84, 0xf2, 0x33, 0xf3, 0x4a, 0x52, 0x8b, 0xd2, 0x12, 0x93,
	0x53, 0x95, 0xb4, 0xb8, 0xc4, 0x9c, 0x41, 0xaa, 0x43, 0x12, 0x8b, 0xb3, 0x9d, 0x8b, 0x52, 0x13,
	0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x72,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0xa5, 0x08, 0x2e, 0x71, 0x0c, 0xb5, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xb6, 0x5c, 0x5c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0xc9,
	0xf9, 0x29, 0xa9, 0x60, 0x3d, 0x7c, 0x46, 0xb2, 0x7a, 0x18, 0xd6, 0xe9, 0x85, 0x06, 0xf9, 0xc4,
	0x07, 0x87, 0x38, 0x86, 0x84, 0x06, 0x07, 0x21, 0x69, 0xd0, 0x52, 0xe4, 0xe2, 0x42, 0xc8, 0x08,
	0xb1, 0x71, 0x31, 0xe5, 0x67, 0x0b, 0x30, 0x08, 0x71, 0x73, 0xb1, 0xa7, 0x25, 0x66, 0xe6, 0x94,
	0x16, 0xa5, 0x0a, 0x30, 0x1a, 0x55, 0x71, 0x09, 0xc2, 0x7c, 0xe3, 0x09, 0x33, 0x4e, 0x28, 0x95,
	0x8b, 0x0b, 0xe2, 0x10, 0x90, 0x93, 0x84, 0x34, 0xb1, 0x58, 0x88, 0xdd, 0x73, 0x52, 0x5a, 0xc4,
	0x28, 0x85, 0xf8, 0x4d, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0x7c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0c, 0xe1, 0x55, 0x19, 0x59, 0x01, 0x00, 0x00,
}
