// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: crawlerToAnalyser.proto

package analyserinterface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AnalyserInterface service

type AnalyserInterfaceService interface {
	// Create a Task which should be crawled by sherlock crawler.
	CreateTask(ctx context.Context, in *CrawlTaskCreateRequest, opts ...client.CallOption) (*CrawlTaskCreateResponse, error)
}

type analyserInterfaceService struct {
	c    client.Client
	name string
}

func NewAnalyserInterfaceService(name string, c client.Client) AnalyserInterfaceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "analyserinterface"
	}
	return &analyserInterfaceService{
		c:    c,
		name: name,
	}
}

func (c *analyserInterfaceService) CreateTask(ctx context.Context, in *CrawlTaskCreateRequest, opts ...client.CallOption) (*CrawlTaskCreateResponse, error) {
	req := c.c.NewRequest(c.name, "AnalyserInterface.CreateTask", in)
	out := new(CrawlTaskCreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AnalyserInterface service

type AnalyserInterfaceHandler interface {
	// Create a Task which should be crawled by sherlock crawler.
	CreateTask(context.Context, *CrawlTaskCreateRequest, *CrawlTaskCreateResponse) error
}

func RegisterAnalyserInterfaceHandler(s server.Server, hdlr AnalyserInterfaceHandler, opts ...server.HandlerOption) error {
	type analyserInterface interface {
		CreateTask(ctx context.Context, in *CrawlTaskCreateRequest, out *CrawlTaskCreateResponse) error
	}
	type AnalyserInterface struct {
		analyserInterface
	}
	h := &analyserInterfaceHandler{hdlr}
	return s.Handle(s.NewHandler(&AnalyserInterface{h}, opts...))
}

type analyserInterfaceHandler struct {
	AnalyserInterfaceHandler
}

func (h *analyserInterfaceHandler) CreateTask(ctx context.Context, in *CrawlTaskCreateRequest, out *CrawlTaskCreateResponse) error {
	return h.AnalyserInterfaceHandler.CreateTask(ctx, in, out)
}
