// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawlerToAnalyserFileTransfer.proto

package crawlerproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//UploadStatusCode gives information. the receiver sends a ok if he received all chunks.
type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

var UploadStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var UploadStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}

func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{0}
}

//
//Chunk represents a chunk of a http response.
type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	TaskId               uint64   `protobuf:"varint,2,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

//
//Infos represent all information in relation to the http response. it sends all information of a CrawlerTaskRequest that need to be sent once.
type Infos struct {
	TaskId               uint64         `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	Address              string         `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Header               []*HeaderArray `protobuf:"bytes,3,rep,name=Header,proto3" json:"Header,omitempty"`
	StatusCode           int32          `protobuf:"varint,4,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	ResponseTime         int64          `protobuf:"varint,5,opt,name=ResponseTime,proto3" json:"ResponseTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Infos) Reset()         { *m = Infos{} }
func (m *Infos) String() string { return proto.CompactTextString(m) }
func (*Infos) ProtoMessage()    {}
func (*Infos) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{1}
}

func (m *Infos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Infos.Unmarshal(m, b)
}
func (m *Infos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Infos.Marshal(b, m, deterministic)
}
func (m *Infos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Infos.Merge(m, src)
}
func (m *Infos) XXX_Size() int {
	return xxx_messageInfo_Infos.Size(m)
}
func (m *Infos) XXX_DiscardUnknown() {
	xxx_messageInfo_Infos.DiscardUnknown(m)
}

var xxx_messageInfo_Infos proto.InternalMessageInfo

func (m *Infos) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Infos) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Infos) GetHeader() []*HeaderArray {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Infos) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Infos) GetResponseTime() int64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

//
//HeaderArray consists of keys and values
type HeaderArray struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderArray) Reset()         { *m = HeaderArray{} }
func (m *HeaderArray) String() string { return proto.CompactTextString(m) }
func (*HeaderArray) ProtoMessage()    {}
func (*HeaderArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{2}
}

func (m *HeaderArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderArray.Unmarshal(m, b)
}
func (m *HeaderArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderArray.Marshal(b, m, deterministic)
}
func (m *HeaderArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderArray.Merge(m, src)
}
func (m *HeaderArray) XXX_Size() int {
	return xxx_messageInfo_HeaderArray.Size(m)
}
func (m *HeaderArray) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderArray.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderArray proto.InternalMessageInfo

func (m *HeaderArray) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeaderArray) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

//
//ErrorCase will be sent if there is a Taskerror in a CrawlerTaskRequest. no body will be sent in this case.
type ErrorCase struct {
	TaskId               uint64   `protobuf:"varint,1,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	TaskError            string   `protobuf:"bytes,3,opt,name=TaskError,proto3" json:"TaskError,omitempty"`
	ResponseTime         int64    `protobuf:"varint,4,opt,name=ResponseTime,proto3" json:"ResponseTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorCase) Reset()         { *m = ErrorCase{} }
func (m *ErrorCase) String() string { return proto.CompactTextString(m) }
func (*ErrorCase) ProtoMessage()    {}
func (*ErrorCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{3}
}

func (m *ErrorCase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCase.Unmarshal(m, b)
}
func (m *ErrorCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCase.Marshal(b, m, deterministic)
}
func (m *ErrorCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCase.Merge(m, src)
}
func (m *ErrorCase) XXX_Size() int {
	return xxx_messageInfo_ErrorCase.Size(m)
}
func (m *ErrorCase) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCase.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCase proto.InternalMessageInfo

func (m *ErrorCase) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *ErrorCase) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ErrorCase) GetTaskError() string {
	if m != nil {
		return m.TaskError
	}
	return ""
}

func (m *ErrorCase) GetResponseTime() int64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

//
//UploadStatus is the response from the receiver.
type UploadStatus struct {
	Message              string           `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Code                 UploadStatusCode `protobuf:"varint,2,opt,name=Code,proto3,enum=crawlerproto.UploadStatusCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadStatus) Reset()         { *m = UploadStatus{} }
func (m *UploadStatus) String() string { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()    {}
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{4}
}

func (m *UploadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatus.Unmarshal(m, b)
}
func (m *UploadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatus.Marshal(b, m, deterministic)
}
func (m *UploadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatus.Merge(m, src)
}
func (m *UploadStatus) XXX_Size() int {
	return xxx_messageInfo_UploadStatus.Size(m)
}
func (m *UploadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatus proto.InternalMessageInfo

func (m *UploadStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadStatus) GetCode() UploadStatusCode {
	if m != nil {
		return m.Code
	}
	return UploadStatusCode_Unknown
}

func init() {
	proto.RegisterEnum("crawlerproto.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
	proto.RegisterType((*Chunk)(nil), "crawlerproto.Chunk")
	proto.RegisterType((*Infos)(nil), "crawlerproto.Infos")
	proto.RegisterType((*HeaderArray)(nil), "crawlerproto.HeaderArray")
	proto.RegisterType((*ErrorCase)(nil), "crawlerproto.ErrorCase")
	proto.RegisterType((*UploadStatus)(nil), "crawlerproto.UploadStatus")
}

func init() {
	proto.RegisterFile("crawlerToAnalyserFileTransfer.proto", fileDescriptor_6af6f45688fe9b43)
}

var fileDescriptor_6af6f45688fe9b43 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0x34, 0x1f, 0xab, 0x4c, 0x22, 0x88, 0x0c, 0x82, 0xb0, 0x42, 0xab, 0x55, 0xb8, 0x54,
	0x1c, 0x2a, 0x91, 0x15, 0x07, 0x0e, 0x48, 0x54, 0x11, 0xab, 0xad, 0x10, 0x42, 0x72, 0x53, 0x4e,
	0x5c, 0x0c, 0x99, 0x42, 0x95, 0x60, 0x57, 0x76, 0xaa, 0xaa, 0x27, 0xfe, 0x12, 0xff, 0x85, 0x3f,
	0x44, 0xec, 0xa4, 0x34, 0x29, 0xd0, 0xc3, 0xde, 0xfc, 0xde, 0xbc, 0x79, 0x7e, 0x63, 0x0f, 0x3c,
	0xfb, 0x22, 0xd9, 0xb6, 0x42, 0x99, 0x8b, 0x29, 0x67, 0xd5, 0x4e, 0xa1, 0xbc, 0x59, 0x55, 0x98,
	0x4b, 0xc6, 0xd5, 0x12, 0xe5, 0x64, 0x2d, 0x45, 0x2d, 0x48, 0xd8, 0x89, 0x0c, 0x4a, 0x5e, 0x81,
	0x9b, 0x7d, 0xdb, 0xf0, 0x92, 0xc4, 0x70, 0x9e, 0x09, 0x5e, 0x23, 0xaf, 0x63, 0xeb, 0xca, 0x1a,
	0x87, 0x74, 0x0f, 0xc9, 0x23, 0xf0, 0x72, 0xa6, 0xca, 0x59, 0x11, 0x8f, 0x9a, 0x82, 0x43, 0x3b,
	0x94, 0xfc, 0xb4, 0xc0, 0x9d, 0xf1, 0xa5, 0x50, 0x3d, 0x85, 0xd5, 0x57, 0x68, 0xcf, 0x69, 0x51,
	0x48, 0x54, 0xca, 0xb4, 0xfa, 0x74, 0x0f, 0xc9, 0x0b, 0xf0, 0x6e, 0x91, 0x15, 0x28, 0x63, 0xfb,
	0xca, 0x1e, 0x07, 0xe9, 0x93, 0x49, 0x3f, 0xd5, 0xa4, 0xad, 0x4d, 0xa5, 0x64, 0x3b, 0xda, 0x09,
	0xc9, 0x25, 0xc0, 0xbc, 0x66, 0xf5, 0x46, 0x65, 0xa2, 0xc0, 0xd8, 0x69, 0xfc, 0x5c, 0xda, 0x63,
	0x48, 0x02, 0x21, 0x45, 0xb5, 0x16, 0x5c, 0x61, 0xbe, 0xfa, 0x8e, 0xb1, 0xdb, 0x28, 0x6c, 0x3a,
	0xe0, 0x92, 0x97, 0x10, 0xf4, 0xac, 0x49, 0x04, 0xf6, 0x3b, 0xdc, 0x99, 0xd0, 0x3e, 0xd5, 0x47,
	0xf2, 0x10, 0xdc, 0x8f, 0xac, 0xda, 0x60, 0x97, 0xb7, 0x05, 0xc9, 0x0f, 0xf0, 0xdf, 0x4a, 0x29,
	0x64, 0xc6, 0x14, 0xde, 0x61, 0xd8, 0xa7, 0xe0, 0x6b, 0x8d, 0xb1, 0x68, 0xe6, 0xd5, 0xb5, 0x03,
	0xf1, 0x57, 0x6e, 0xe7, 0x1f, 0xb9, 0x3f, 0x41, 0xb8, 0x58, 0x57, 0x82, 0x15, 0xed, 0xbc, 0xfa,
	0xae, 0xf7, 0x8d, 0x33, 0xfb, 0x8a, 0x5d, 0xf8, 0x3d, 0x24, 0x29, 0x38, 0xe6, 0x7d, 0x74, 0x84,
	0x7b, 0xe9, 0xe5, 0xf0, 0x59, 0xfb, 0x1e, 0x5a, 0x45, 0x8d, 0xf6, 0xf9, 0x35, 0x44, 0xc7, 0x15,
	0x12, 0xc0, 0xf9, 0x82, 0x97, 0x5c, 0x6c, 0x79, 0x74, 0x46, 0x3c, 0x18, 0x7d, 0x28, 0x23, 0x8b,
	0x00, 0x78, 0x37, 0xac, 0xd9, 0xa8, 0x22, 0x1a, 0xa5, 0xbf, 0x2c, 0xf0, 0xe6, 0xc8, 0xf5, 0xcf,
	0xbc, 0x06, 0xaf, 0xed, 0x27, 0x0f, 0x86, 0xf7, 0x99, 0xcd, 0xba, 0xb8, 0xf8, 0x7f, 0x88, 0xe4,
	0x6c, 0x6c, 0x91, 0x37, 0x10, 0xb4, 0x5c, 0xbb, 0x4c, 0x47, 0x1e, 0x86, 0x3c, 0xed, 0x41, 0x6e,
	0xe1, 0x7e, 0xcb, 0x1c, 0x7e, 0xe9, 0xf1, 0xb0, 0xe1, 0x4f, 0xe1, 0xb4, 0xd3, 0x67, 0xcf, 0xb0,
	0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x13, 0x5b, 0x46, 0xca, 0x4a, 0x03, 0x00, 0x00,
}
