// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawlerToAnalyserFileTransfer.proto

package crawlerproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//UploadStatusCode gives information. the receiver sends a ok if he received all chunks.
type UploadStatusCode int32

const (
	UploadStatusCode_Ok     UploadStatusCode = 0
	UploadStatusCode_Failed UploadStatusCode = 1
)

var UploadStatusCode_name = map[int32]string{
	0: "Ok",
	1: "Failed",
}

var UploadStatusCode_value = map[string]int32{
	"Ok":     0,
	"Failed": 1,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}

func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{0}
}

//
//Chunk represents a chunk of a http response.
type Chunk struct {
	Content              []byte         `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	TaskId               uint64         `protobuf:"varint,2,opt,name=TaskId,proto3" json:"TaskId,omitempty"`
	Address              string         `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	TaskError            string         `protobuf:"bytes,4,opt,name=TaskError,proto3" json:"TaskError,omitempty"`
	Header               []*HeaderArray `protobuf:"bytes,5,rep,name=Header,proto3" json:"Header,omitempty"`
	StatusCode           int32          `protobuf:"varint,6,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	ResponseTime         int64          `protobuf:"varint,7,opt,name=ResponseTime,proto3" json:"ResponseTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Chunk) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Chunk) GetTaskError() string {
	if m != nil {
		return m.TaskError
	}
	return ""
}

func (m *Chunk) GetHeader() []*HeaderArray {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Chunk) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Chunk) GetResponseTime() int64 {
	if m != nil {
		return m.ResponseTime
	}
	return 0
}

//
//HeaderArray consists of keys and values
type HeaderArray struct {
	Key                  string              `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ValueArr             []*HeaderArrayValue `protobuf:"bytes,2,rep,name=ValueArr,proto3" json:"ValueArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HeaderArray) Reset()         { *m = HeaderArray{} }
func (m *HeaderArray) String() string { return proto.CompactTextString(m) }
func (*HeaderArray) ProtoMessage()    {}
func (*HeaderArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{1}
}

func (m *HeaderArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderArray.Unmarshal(m, b)
}
func (m *HeaderArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderArray.Marshal(b, m, deterministic)
}
func (m *HeaderArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderArray.Merge(m, src)
}
func (m *HeaderArray) XXX_Size() int {
	return xxx_messageInfo_HeaderArray.Size(m)
}
func (m *HeaderArray) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderArray.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderArray proto.InternalMessageInfo

func (m *HeaderArray) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeaderArray) GetValueArr() []*HeaderArrayValue {
	if m != nil {
		return m.ValueArr
	}
	return nil
}

//
//HeaderArray consists of keys and values
type HeaderArrayValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderArrayValue) Reset()         { *m = HeaderArrayValue{} }
func (m *HeaderArrayValue) String() string { return proto.CompactTextString(m) }
func (*HeaderArrayValue) ProtoMessage()    {}
func (*HeaderArrayValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{2}
}

func (m *HeaderArrayValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderArrayValue.Unmarshal(m, b)
}
func (m *HeaderArrayValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderArrayValue.Marshal(b, m, deterministic)
}
func (m *HeaderArrayValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderArrayValue.Merge(m, src)
}
func (m *HeaderArrayValue) XXX_Size() int {
	return xxx_messageInfo_HeaderArrayValue.Size(m)
}
func (m *HeaderArrayValue) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderArrayValue.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderArrayValue proto.InternalMessageInfo

func (m *HeaderArrayValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

//
//UploadStatus is the response from the receiver.
type UploadStatus struct {
	Code                 UploadStatusCode `protobuf:"varint,2,opt,name=Code,proto3,enum=crawlerproto.UploadStatusCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadStatus) Reset()         { *m = UploadStatus{} }
func (m *UploadStatus) String() string { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()    {}
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6af6f45688fe9b43, []int{3}
}

func (m *UploadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatus.Unmarshal(m, b)
}
func (m *UploadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatus.Marshal(b, m, deterministic)
}
func (m *UploadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatus.Merge(m, src)
}
func (m *UploadStatus) XXX_Size() int {
	return xxx_messageInfo_UploadStatus.Size(m)
}
func (m *UploadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatus proto.InternalMessageInfo

func (m *UploadStatus) GetCode() UploadStatusCode {
	if m != nil {
		return m.Code
	}
	return UploadStatusCode_Ok
}

func init() {
	proto.RegisterEnum("crawlerproto.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
	proto.RegisterType((*Chunk)(nil), "crawlerproto.Chunk")
	proto.RegisterType((*HeaderArray)(nil), "crawlerproto.HeaderArray")
	proto.RegisterType((*HeaderArrayValue)(nil), "crawlerproto.HeaderArrayValue")
	proto.RegisterType((*UploadStatus)(nil), "crawlerproto.UploadStatus")
}

func init() {
	proto.RegisterFile("crawlerToAnalyserFileTransfer.proto", fileDescriptor_6af6f45688fe9b43)
}

var fileDescriptor_6af6f45688fe9b43 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xd1, 0x4b, 0xeb, 0x30,
	0x14, 0xc6, 0xd7, 0x75, 0xcd, 0xee, 0xce, 0xca, 0xa5, 0xe4, 0x5e, 0x2e, 0xb9, 0x43, 0xc6, 0xa8,
	0x20, 0xc5, 0x87, 0xa1, 0xf3, 0xcd, 0x17, 0x99, 0xc3, 0xe1, 0xf0, 0x41, 0xc8, 0xaa, 0x2f, 0x3e,
	0x45, 0x7b, 0xc4, 0xb1, 0xda, 0x8c, 0xa4, 0x43, 0xf6, 0x1f, 0xfb, 0x67, 0xd8, 0xa4, 0x9d, 0x76,
	0x83, 0xbd, 0xe5, 0x3b, 0xdf, 0x2f, 0x39, 0xdf, 0xc9, 0x81, 0xe3, 0x17, 0x25, 0x3e, 0x52, 0x54,
	0xb1, 0x1c, 0x67, 0x22, 0xdd, 0x68, 0x54, 0xd3, 0x45, 0x8a, 0xb1, 0x12, 0x99, 0x7e, 0x45, 0x35,
	0x5c, 0x29, 0x99, 0x4b, 0xea, 0x57, 0x90, 0x55, 0xe1, 0xa7, 0x03, 0xde, 0xe4, 0x6d, 0x9d, 0x2d,
	0x29, 0x83, 0xf6, 0x44, 0x66, 0x39, 0x66, 0x39, 0x73, 0x06, 0x4e, 0xe4, 0xf3, 0xad, 0xa4, 0xff,
	0x80, 0xc4, 0x42, 0x2f, 0x67, 0x09, 0x6b, 0x16, 0x46, 0x8b, 0x57, 0xca, 0xdc, 0x18, 0x27, 0x89,
	0x42, 0xad, 0x99, 0x5b, 0x18, 0x1d, 0xbe, 0x95, 0xf4, 0x08, 0x3a, 0x86, 0xb9, 0x51, 0x4a, 0x2a,
	0xd6, 0xb2, 0xde, 0x4f, 0x81, 0x9e, 0x03, 0xb9, 0x45, 0x91, 0xa0, 0x62, 0xde, 0xc0, 0x8d, 0xba,
	0xa3, 0xff, 0xc3, 0x7a, 0xa4, 0x61, 0xe9, 0x8d, 0x95, 0x12, 0x1b, 0x5e, 0x81, 0xb4, 0x0f, 0x30,
	0xcf, 0x45, 0xbe, 0xd6, 0x13, 0x99, 0x20, 0x23, 0xc5, 0x8b, 0x1e, 0xaf, 0x55, 0x68, 0x08, 0x3e,
	0x47, 0xbd, 0x92, 0x99, 0xc6, 0x78, 0xf1, 0x8e, 0xac, 0x5d, 0x10, 0x2e, 0xdf, 0xa9, 0x85, 0x4f,
	0xd0, 0xad, 0x3d, 0x4d, 0x03, 0x70, 0xef, 0x70, 0x63, 0x67, 0xed, 0x70, 0x73, 0xa4, 0x97, 0xf0,
	0xeb, 0x51, 0xa4, 0x6b, 0x2c, 0xfc, 0x62, 0x52, 0x93, 0xac, 0x7f, 0x30, 0x99, 0x05, 0xf9, 0x37,
	0x1f, 0x46, 0x10, 0xec, 0xbb, 0xf4, 0x2f, 0x78, 0xf6, 0x50, 0xf5, 0x28, 0x45, 0x78, 0x0d, 0xfe,
	0xc3, 0x2a, 0x95, 0x22, 0x29, 0xe3, 0xd3, 0x11, 0xb4, 0xec, 0x50, 0xe6, 0x6f, 0x7f, 0xef, 0x77,
	0xac, 0x93, 0x86, 0xe2, 0x96, 0x3d, 0x3d, 0x81, 0x60, 0xdf, 0xa1, 0x04, 0x9a, 0xf7, 0xcb, 0xa0,
	0x41, 0x01, 0xc8, 0x54, 0x14, 0x6b, 0x4f, 0x02, 0x67, 0x34, 0x03, 0x32, 0xc7, 0xcc, 0x7c, 0xe0,
	0x15, 0x90, 0xf2, 0x06, 0xfd, 0xb3, 0xdb, 0xc1, 0x2e, 0xbf, 0xd7, 0x3b, 0xdc, 0x36, 0x6c, 0x44,
	0xce, 0x99, 0xf3, 0x4c, 0xac, 0x73, 0xf1, 0x15, 0x00, 0x00, 0xff, 0xff, 0xff, 0x72, 0xfa, 0x12,
	0x64, 0x02, 0x00, 0x00,
}
