// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package crawlerproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Status of the Crawler.
type ServiceStatus int32

const (
	ServiceStatus_DONE ServiceStatus = 0
)

var ServiceStatus_name = map[int32]string{
	0: "DONE",
}

var ServiceStatus_value = map[string]int32{
	"DONE": 0,
}

func (x ServiceStatus) String() string {
	return proto.EnumName(ServiceStatus_name, int32(x))
}

func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

//
//part of the file
type Chunk struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

//
//SubmitURLRequest will submit a URL.
type SubmitURLRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLRequest) Reset()         { *m = SubmitURLRequest{} }
func (m *SubmitURLRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitURLRequest) ProtoMessage()    {}
func (*SubmitURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{1}
}

func (m *SubmitURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLRequest.Unmarshal(m, b)
}
func (m *SubmitURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLRequest.Marshal(b, m, deterministic)
}
func (m *SubmitURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLRequest.Merge(m, src)
}
func (m *SubmitURLRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitURLRequest.Size(m)
}
func (m *SubmitURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLRequest proto.InternalMessageInfo

func (m *SubmitURLRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

//
//SubmitURLResponse will answer a SubmitURLRequest with a bool to indecate the status of the request.
type SubmitURLResponse struct {
	Recieved             bool     `protobuf:"varint,1,opt,name=recieved,proto3" json:"recieved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLResponse) Reset()         { *m = SubmitURLResponse{} }
func (m *SubmitURLResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitURLResponse) ProtoMessage()    {}
func (*SubmitURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{2}
}

func (m *SubmitURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLResponse.Unmarshal(m, b)
}
func (m *SubmitURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLResponse.Marshal(b, m, deterministic)
}
func (m *SubmitURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLResponse.Merge(m, src)
}
func (m *SubmitURLResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitURLResponse.Size(m)
}
func (m *SubmitURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLResponse proto.InternalMessageInfo

func (m *SubmitURLResponse) GetRecieved() bool {
	if m != nil {
		return m.Recieved
	}
	return false
}

//
//Will submit the Status of the Crawler.
type StatusMessage struct {
	Status               ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=crawlerproto.ServiceStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{3}
}

func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (m *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(m, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetStatus() ServiceStatus {
	if m != nil {
		return m.Status
	}
	return ServiceStatus_DONE
}

func init() {
	proto.RegisterEnum("crawlerproto.ServiceStatus", ServiceStatus_name, ServiceStatus_value)
	proto.RegisterType((*Chunk)(nil), "crawlerproto.Chunk")
	proto.RegisterType((*SubmitURLRequest)(nil), "crawlerproto.SubmitURLRequest")
	proto.RegisterType((*SubmitURLResponse)(nil), "crawlerproto.SubmitURLResponse")
	proto.RegisterType((*StatusMessage)(nil), "crawlerproto.StatusMessage")
}

func init() {
	proto.RegisterFile("crawler.proto", fileDescriptor_84c7eabcfe7807d1)
}

var fileDescriptor_84c7eabcfe7807d1 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x90, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0x99, 0x7c, 0x1f, 0x88, 0x37, 0xa0, 0x58, 0x8d, 0xd1, 0x21, 0xfe, 0x49, 0xe3, 0xc2,
	0xb8, 0x28, 0x06, 0x76, 0x6e, 0x01, 0xe3, 0x42, 0x25, 0x29, 0xf1, 0x01, 0x60, 0xb8, 0x0e, 0x8d,
	0xd0, 0x19, 0xa7, 0x2d, 0xc6, 0xb7, 0xf5, 0x51, 0xec, 0xb4, 0xa8, 0xe3, 0x24, 0xac, 0xdc, 0xf5,
	0xb4, 0xe7, 0xfe, 0x7a, 0xcf, 0x81, 0x66, 0x94, 0x4d, 0xde, 0x16, 0x98, 0xb1, 0x34, 0x4b, 0x74,
	0x42, 0x1a, 0x6b, 0xe9, 0x54, 0xd8, 0x8e, 0x93, 0x24, 0x5e, 0x60, 0xc7, 0xa9, 0xa9, 0x79, 0xee,
	0xe0, 0x32, 0xd5, 0xef, 0xde, 0x4a, 0x4f, 0xa0, 0xda, 0x9f, 0x1b, 0xf9, 0x42, 0x0e, 0xa0, 0x1a,
	0xe5, 0x87, 0xa3, 0xe0, 0x3c, 0xb8, 0x6c, 0x70, 0x2f, 0xe8, 0x05, 0xb4, 0xc6, 0x66, 0xba, 0x14,
	0xfa, 0x89, 0xdf, 0x73, 0x7c, 0x35, 0xa8, 0x34, 0x69, 0xc1, 0x3f, 0xab, 0x9c, 0x6f, 0x9b, 0xe7,
	0x47, 0xda, 0x81, 0xbd, 0x82, 0x4b, 0xa5, 0x89, 0x54, 0x48, 0x42, 0xa8, 0x67, 0x18, 0x09, 0x5c,
	0xe1, 0xcc, 0x79, 0xeb, 0xfc, 0x5b, 0xd3, 0x01, 0x34, 0xc7, 0x7a, 0xa2, 0x8d, 0x7a, 0x40, 0xa5,
	0x26, 0x31, 0x92, 0x1e, 0xd4, 0x94, 0xbb, 0x70, 0xd6, 0x9d, 0x6e, 0x9b, 0x15, 0x23, 0xb0, 0x31,
	0x66, 0x2b, 0x11, 0xa1, 0x9f, 0xe1, 0x6b, 0xeb, 0xd5, 0xb1, 0xa5, 0x14, 0x1f, 0x48, 0x1d, 0xfe,
	0x0f, 0x46, 0x8f, 0xc3, 0x56, 0xa5, 0xfb, 0x11, 0xc0, 0x56, 0xdf, 0x13, 0xc8, 0x08, 0x80, 0xfb,
	0x8f, 0xed, 0x7a, 0xe4, 0xb4, 0x44, 0x2e, 0xa5, 0x0b, 0xcf, 0x36, 0xbe, 0xfb, 0x5c, 0xb4, 0x42,
	0xee, 0x60, 0xf7, 0x56, 0x48, 0xa1, 0xe6, 0x38, 0xe3, 0x46, 0x4a, 0x21, 0x63, 0x72, 0xc8, 0x7c,
	0xc9, 0xec, 0xab, 0x64, 0x36, 0xcc, 0x4b, 0x0e, 0xcb, 0x39, 0x8a, 0xa1, 0x2d, 0xe9, 0xc6, 0x6e,
	0x99, 0xf7, 0x6c, 0xb7, 0xdc, 0x44, 0xd8, 0xff, 0x4d, 0x70, 0x76, 0x5a, 0xb9, 0x0e, 0xba, 0xc3,
	0x9f, 0xd9, 0x3f, 0x60, 0xa6, 0x35, 0x77, 0xd1, 0xfb, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x23, 0x89,
	0x6d, 0xc9, 0x43, 0x02, 0x00, 0x00,
}
