// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analysertowebserver.proto

package analysertowebserver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusRequest) Reset()         { *m = TaskStatusRequest{} }
func (m *TaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*TaskStatusRequest) ProtoMessage()    {}
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fab8dae5c0a05cf, []int{0}
}

func (m *TaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusRequest.Unmarshal(m, b)
}
func (m *TaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *TaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusRequest.Merge(m, src)
}
func (m *TaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_TaskStatusRequest.Size(m)
}
func (m *TaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusRequest proto.InternalMessageInfo

type TaskStatusResponse struct {
	Website              string   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Undone               uint64   `protobuf:"varint,2,opt,name=undone,proto3" json:"undone,omitempty"`
	Processing           uint64   `protobuf:"varint,3,opt,name=processing,proto3" json:"processing,omitempty"`
	CrawlerError         uint64   `protobuf:"varint,4,opt,name=crawlerError,proto3" json:"crawlerError,omitempty"`
	Saving               uint64   `protobuf:"varint,5,opt,name=saving,proto3" json:"saving,omitempty"`
	SendToCrawler        uint64   `protobuf:"varint,6,opt,name=sendToCrawler,proto3" json:"sendToCrawler,omitempty"`
	Finished             uint64   `protobuf:"varint,7,opt,name=finished,proto3" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusResponse) Reset()         { *m = TaskStatusResponse{} }
func (m *TaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatusResponse) ProtoMessage()    {}
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fab8dae5c0a05cf, []int{1}
}

func (m *TaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusResponse.Unmarshal(m, b)
}
func (m *TaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *TaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusResponse.Merge(m, src)
}
func (m *TaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatusResponse.Size(m)
}
func (m *TaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusResponse proto.InternalMessageInfo

func (m *TaskStatusResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *TaskStatusResponse) GetUndone() uint64 {
	if m != nil {
		return m.Undone
	}
	return 0
}

func (m *TaskStatusResponse) GetProcessing() uint64 {
	if m != nil {
		return m.Processing
	}
	return 0
}

func (m *TaskStatusResponse) GetCrawlerError() uint64 {
	if m != nil {
		return m.CrawlerError
	}
	return 0
}

func (m *TaskStatusResponse) GetSaving() uint64 {
	if m != nil {
		return m.Saving
	}
	return 0
}

func (m *TaskStatusResponse) GetSendToCrawler() uint64 {
	if m != nil {
		return m.SendToCrawler
	}
	return 0
}

func (m *TaskStatusResponse) GetFinished() uint64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskStatusRequest)(nil), "analysertowebserver.TaskStatusRequest")
	proto.RegisterType((*TaskStatusResponse)(nil), "analysertowebserver.TaskStatusResponse")
}

func init() {
	proto.RegisterFile("analysertowebserver.proto", fileDescriptor_4fab8dae5c0a05cf)
}

var fileDescriptor_4fab8dae5c0a05cf = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x51, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0x76, 0xb5, 0x6e, 0xeb, 0xa0, 0x87, 0x4e, 0x41, 0x62, 0x0f, 0x22, 0x8b, 0xa8, 0xa7, 0x1e,
	0xf4, 0x09, 0x44, 0x3c, 0x8b, 0x6b, 0x5f, 0x20, 0xed, 0xce, 0xea, 0x62, 0x49, 0xea, 0x4c, 0xd2,
	0xe2, 0xfb, 0xfa, 0x20, 0x6e, 0x92, 0x2a, 0x2d, 0x2e, 0x78, 0x0a, 0xdf, 0xcf, 0x4c, 0xf8, 0xbe,
	0x81, 0x33, 0x6d, 0xf4, 0xe2, 0x53, 0x88, 0x9d, 0x5d, 0xd3, 0xac, 0x7d, 0x57, 0xc4, 0x93, 0x25,
	0x5b, 0x67, 0x71, 0xd4, 0x21, 0x15, 0x23, 0x18, 0x4e, 0xb5, 0xbc, 0xbf, 0x38, 0xed, 0xbc, 0x94,
	0xf4, 0xe1, 0x49, 0x5c, 0xf1, 0x95, 0x01, 0x6e, 0xb3, 0xb2, 0xb4, 0x46, 0x08, 0x15, 0xf4, 0xc3,
	0x60, 0xe3, 0x48, 0x65, 0x17, 0xd9, 0xcd, 0x51, 0xf9, 0x03, 0xf1, 0x14, 0x72, 0x6f, 0x2a, 0x6b,
	0x48, 0xed, 0xb7, 0x42, 0xaf, 0xdc, 0x20, 0x3c, 0x07, 0x68, 0xff, 0x9e, 0x93, 0x48, 0x63, 0x5e,
	0xd5, 0x41, 0xd4, 0xb6, 0x18, 0x2c, 0xe0, 0x78, 0xce, 0x7a, 0xbd, 0x20, 0x7e, 0x64, 0xb6, 0xac,
	0x7a, 0xd1, 0xb1, 0xc3, 0x85, 0xdd, 0xa2, 0x57, 0x61, 0xfe, 0x30, 0xed, 0x4e, 0x08, 0x2f, 0xe1,
	0x44, 0xc8, 0x54, 0x53, 0xfb, 0x90, 0xdc, 0x2a, 0x8f, 0xf2, 0x2e, 0x89, 0x63, 0x18, 0xd4, 0x8d,
	0x69, 0xe4, 0x8d, 0x2a, 0xd5, 0x8f, 0x86, 0x5f, 0x7c, 0xcb, 0x30, 0xb8, 0xdf, 0x54, 0x82, 0x35,
	0x0c, 0x53, 0xda, 0xa7, 0x3a, 0x24, 0x7f, 0xf6, 0xe4, 0x09, 0xaf, 0x26, 0x5d, 0x6d, 0xfe, 0xe9,
	0x6b, 0x7c, 0xfd, 0xaf, 0x2f, 0x35, 0x58, 0xec, 0xcd, 0xf2, 0x78, 0x8b, 0xbb, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xdc, 0x93, 0xc6, 0x2c, 0xa8, 0x01, 0x00, 0x00,
}
