// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyser.proto

package analyserproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("analyser.proto", fileDescriptor_18bf88fceba00cff)
}

var fileDescriptor_18bf88fceba00cff = []byte{
	// 57 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcc, 0x4b, 0xcc,
	0xa9, 0x2c, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0xf1, 0xc1, 0x5c,
	0x23, 0x2e, 0x2e, 0x0e, 0x47, 0xa8, 0x40, 0x12, 0x1b, 0x58, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0xcd, 0x16, 0x56, 0x33, 0x00, 0x00, 0x00,
}
