// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: analyser.proto

package analyserproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Analyser service

type AnalyserService interface {
}

type analyserService struct {
	c    client.Client
	name string
}

func NewAnalyserService(name string, c client.Client) AnalyserService {
	return &analyserService{
		c:    c,
		name: name,
	}
}

// Server API for Analyser service

type AnalyserHandler interface {
}

func RegisterAnalyserHandler(s server.Server, hdlr AnalyserHandler, opts ...server.HandlerOption) error {
	type analyser interface {
	}
	type Analyser struct {
		analyser
	}
	h := &analyserHandler{hdlr}
	return s.Handle(s.NewHandler(&Analyser{h}, opts...))
}

type analyserHandler struct {
	AnalyserHandler
}
