// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyser.proto

package analyserproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnalyserTaskCreateRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyserTaskCreateRequest) Reset()         { *m = AnalyserTaskCreateRequest{} }
func (m *AnalyserTaskCreateRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyserTaskCreateRequest) ProtoMessage()    {}
func (*AnalyserTaskCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf88fceba00cff, []int{0}
}

func (m *AnalyserTaskCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyserTaskCreateRequest.Unmarshal(m, b)
}
func (m *AnalyserTaskCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyserTaskCreateRequest.Marshal(b, m, deterministic)
}
func (m *AnalyserTaskCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyserTaskCreateRequest.Merge(m, src)
}
func (m *AnalyserTaskCreateRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyserTaskCreateRequest.Size(m)
}
func (m *AnalyserTaskCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyserTaskCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyserTaskCreateRequest proto.InternalMessageInfo

func (m *AnalyserTaskCreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AnalyserTaskCreateResponse struct {
	Taskid               uint64   `protobuf:"varint,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyserTaskCreateResponse) Reset()         { *m = AnalyserTaskCreateResponse{} }
func (m *AnalyserTaskCreateResponse) String() string { return proto.CompactTextString(m) }
func (*AnalyserTaskCreateResponse) ProtoMessage()    {}
func (*AnalyserTaskCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf88fceba00cff, []int{1}
}

func (m *AnalyserTaskCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyserTaskCreateResponse.Unmarshal(m, b)
}
func (m *AnalyserTaskCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyserTaskCreateResponse.Marshal(b, m, deterministic)
}
func (m *AnalyserTaskCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyserTaskCreateResponse.Merge(m, src)
}
func (m *AnalyserTaskCreateResponse) XXX_Size() int {
	return xxx_messageInfo_AnalyserTaskCreateResponse.Size(m)
}
func (m *AnalyserTaskCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyserTaskCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyserTaskCreateResponse proto.InternalMessageInfo

func (m *AnalyserTaskCreateResponse) GetTaskid() uint64 {
	if m != nil {
		return m.Taskid
	}
	return 0
}

type TaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusRequest) Reset()         { *m = TaskStatusRequest{} }
func (m *TaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*TaskStatusRequest) ProtoMessage()    {}
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf88fceba00cff, []int{2}
}

func (m *TaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusRequest.Unmarshal(m, b)
}
func (m *TaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *TaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusRequest.Merge(m, src)
}
func (m *TaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_TaskStatusRequest.Size(m)
}
func (m *TaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusRequest proto.InternalMessageInfo

type TaskStatusResponse struct {
	Website              string   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Undone               uint64   `protobuf:"varint,2,opt,name=undone,proto3" json:"undone,omitempty"`
	Processing           uint64   `protobuf:"varint,3,opt,name=processing,proto3" json:"processing,omitempty"`
	Finished             uint64   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusResponse) Reset()         { *m = TaskStatusResponse{} }
func (m *TaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatusResponse) ProtoMessage()    {}
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bf88fceba00cff, []int{3}
}

func (m *TaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusResponse.Unmarshal(m, b)
}
func (m *TaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *TaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusResponse.Merge(m, src)
}
func (m *TaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatusResponse.Size(m)
}
func (m *TaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusResponse proto.InternalMessageInfo

func (m *TaskStatusResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *TaskStatusResponse) GetUndone() uint64 {
	if m != nil {
		return m.Undone
	}
	return 0
}

func (m *TaskStatusResponse) GetProcessing() uint64 {
	if m != nil {
		return m.Processing
	}
	return 0
}

func (m *TaskStatusResponse) GetFinished() uint64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func init() {
	proto.RegisterType((*AnalyserTaskCreateRequest)(nil), "analyserproto.AnalyserTaskCreateRequest")
	proto.RegisterType((*AnalyserTaskCreateResponse)(nil), "analyserproto.AnalyserTaskCreateResponse")
	proto.RegisterType((*TaskStatusRequest)(nil), "analyserproto.TaskStatusRequest")
	proto.RegisterType((*TaskStatusResponse)(nil), "analyserproto.TaskStatusResponse")
}

func init() {
	proto.RegisterFile("analyser.proto", fileDescriptor_18bf88fceba00cff)
}

var fileDescriptor_18bf88fceba00cff = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x50, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x25, 0xb4, 0x2a, 0xe5, 0x4a, 0x20, 0x7a, 0x91, 0x90, 0xc9, 0x80, 0x8a, 0xa7, 0x32, 0x90,
	0x01, 0xf8, 0x01, 0xc4, 0x07, 0x20, 0x02, 0x13, 0x9b, 0xdb, 0xdc, 0x82, 0x45, 0xe5, 0x94, 0x5c,
	0x5b, 0x88, 0x95, 0xdf, 0xe3, 0xa7, 0xa8, 0x1f, 0x41, 0xe1, 0xa9, 0x6e, 0x3e, 0x0f, 0x1f, 0xfb,
	0x1c, 0xd8, 0x55, 0x46, 0x2d, 0x5e, 0x99, 0x9a, 0x62, 0xd9, 0xd4, 0xb6, 0xc6, 0x9d, 0x16, 0x07,
	0x28, 0x4f, 0xe1, 0xf0, 0x32, 0x11, 0x77, 0x8a, 0x9f, 0xae, 0x1a, 0x52, 0x96, 0x4a, 0x7a, 0x76,
	0xc4, 0x16, 0xf7, 0xa0, 0xe7, 0x9a, 0x85, 0xc8, 0xc6, 0xd9, 0x64, 0xbb, 0xf4, 0x47, 0x79, 0x01,
	0xf9, 0x6f, 0x76, 0x5e, 0xd6, 0x86, 0x09, 0x0f, 0x60, 0x60, 0x57, 0xac, 0xae, 0xc2, 0x95, 0x7e,
	0x99, 0x90, 0xdc, 0x87, 0x91, 0x77, 0xdf, 0x5a, 0x65, 0x1d, 0xa7, 0x70, 0xf9, 0x96, 0x01, 0x76,
	0xd9, 0x94, 0x21, 0x60, 0xeb, 0x85, 0xa6, 0xac, 0x2d, 0xa5, 0x77, 0x5b, 0xe8, 0xd3, 0x9d, 0xa9,
	0x6a, 0x43, 0x62, 0x33, 0xa6, 0x47, 0x84, 0x47, 0x00, 0xab, 0x2e, 0x33, 0x62, 0xd6, 0xe6, 0x41,
	0xf4, 0x82, 0xd6, 0x61, 0x30, 0x87, 0xe1, 0x5c, 0x1b, 0xcd, 0x8f, 0x54, 0x89, 0x7e, 0x50, 0x3f,
	0xf1, 0xd9, 0x7b, 0x06, 0xc3, 0xb6, 0x10, 0xce, 0x00, 0x62, 0x21, 0xff, 0x2d, 0x9c, 0x14, 0x5f,
	0x96, 0x2a, 0xfe, 0x9c, 0x29, 0x3f, 0x59, 0xc3, 0x19, 0xdb, 0xc9, 0x0d, 0xbc, 0x87, 0x51, 0x6c,
	0x7c, 0x3d, 0xf7, 0xfa, 0x8d, 0x23, 0x47, 0x38, 0xfe, 0x96, 0xf0, 0x63, 0xad, 0xfc, 0xf8, 0x1f,
	0x47, 0x9b, 0x3d, 0x1d, 0x04, 0xed, 0xfc, 0x23, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xcf, 0x7a, 0x8d,
	0xf4, 0x01, 0x00, 0x00,
}
