// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawlertowebserver.proto

package crawlerwebserverproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Status of the Crawler.
type ServiceStatus int32

const (
	ServiceStatus_DONE ServiceStatus = 0
)

var ServiceStatus_name = map[int32]string{
	0: "DONE",
}

var ServiceStatus_value = map[string]int32{
	"DONE": 0,
}

func (x ServiceStatus) String() string {
	return proto.EnumName(ServiceStatus_name, int32(x))
}

func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{0}
}

//
//TaskStatusRequest will represent a request for the current status of the tasks.
type TaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusRequest) Reset()         { *m = TaskStatusRequest{} }
func (m *TaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*TaskStatusRequest) ProtoMessage()    {}
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{0}
}

func (m *TaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusRequest.Unmarshal(m, b)
}
func (m *TaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *TaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusRequest.Merge(m, src)
}
func (m *TaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_TaskStatusRequest.Size(m)
}
func (m *TaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusRequest proto.InternalMessageInfo

//
//TaskStatusResponse will represent a response for a TaskStatusRequest.
type TaskStatusResponse struct {
	Website              string   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Undone               uint64   `protobuf:"varint,2,opt,name=undone,proto3" json:"undone,omitempty"`
	Processing           uint64   `protobuf:"varint,3,opt,name=processing,proto3" json:"processing,omitempty"`
	Finished             uint64   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Failed               uint64   `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusResponse) Reset()         { *m = TaskStatusResponse{} }
func (m *TaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatusResponse) ProtoMessage()    {}
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{1}
}

func (m *TaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusResponse.Unmarshal(m, b)
}
func (m *TaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *TaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusResponse.Merge(m, src)
}
func (m *TaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatusResponse.Size(m)
}
func (m *TaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusResponse proto.InternalMessageInfo

func (m *TaskStatusResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *TaskStatusResponse) GetUndone() uint64 {
	if m != nil {
		return m.Undone
	}
	return 0
}

func (m *TaskStatusResponse) GetProcessing() uint64 {
	if m != nil {
		return m.Processing
	}
	return 0
}

func (m *TaskStatusResponse) GetFinished() uint64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func (m *TaskStatusResponse) GetFailed() uint64 {
	if m != nil {
		return m.Failed
	}
	return 0
}

//
//SubmitURLRequest will submit a URL.
type SubmitURLRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLRequest) Reset()         { *m = SubmitURLRequest{} }
func (m *SubmitURLRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitURLRequest) ProtoMessage()    {}
func (*SubmitURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{2}
}

func (m *SubmitURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLRequest.Unmarshal(m, b)
}
func (m *SubmitURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLRequest.Marshal(b, m, deterministic)
}
func (m *SubmitURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLRequest.Merge(m, src)
}
func (m *SubmitURLRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitURLRequest.Size(m)
}
func (m *SubmitURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLRequest proto.InternalMessageInfo

func (m *SubmitURLRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

//
//SubmitURLResponse will answer a SubmitURLRequest with a bool to indecate the status of the request.
type SubmitURLResponse struct {
	Recieved             bool     `protobuf:"varint,1,opt,name=recieved,proto3" json:"recieved,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLResponse) Reset()         { *m = SubmitURLResponse{} }
func (m *SubmitURLResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitURLResponse) ProtoMessage()    {}
func (*SubmitURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{3}
}

func (m *SubmitURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLResponse.Unmarshal(m, b)
}
func (m *SubmitURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLResponse.Marshal(b, m, deterministic)
}
func (m *SubmitURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLResponse.Merge(m, src)
}
func (m *SubmitURLResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitURLResponse.Size(m)
}
func (m *SubmitURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLResponse proto.InternalMessageInfo

func (m *SubmitURLResponse) GetRecieved() bool {
	if m != nil {
		return m.Recieved
	}
	return false
}

func (m *SubmitURLResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("crawlerwebserverproto.ServiceStatus", ServiceStatus_name, ServiceStatus_value)
	proto.RegisterType((*TaskStatusRequest)(nil), "crawlerwebserverproto.TaskStatusRequest")
	proto.RegisterType((*TaskStatusResponse)(nil), "crawlerwebserverproto.TaskStatusResponse")
	proto.RegisterType((*SubmitURLRequest)(nil), "crawlerwebserverproto.SubmitURLRequest")
	proto.RegisterType((*SubmitURLResponse)(nil), "crawlerwebserverproto.SubmitURLResponse")
}

func init() {
	proto.RegisterFile("crawlertowebserver.proto", fileDescriptor_8f1f999edb578de9)
}

var fileDescriptor_8f1f999edb578de9 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x51, 0x4b, 0x4e, 0xeb, 0x40,
	0x10, 0x8c, 0x5f, 0xfe, 0x2d, 0x3d, 0x29, 0x69, 0x3e, 0x1a, 0xb2, 0x40, 0xc8, 0x42, 0x22, 0xb0,
	0xc8, 0x02, 0x8e, 0x00, 0xd9, 0x21, 0x22, 0x26, 0x70, 0x00, 0xc7, 0xe9, 0xc0, 0x40, 0xf0, 0x84,
	0xf9, 0x24, 0x77, 0xe1, 0x64, 0x1c, 0x87, 0xf1, 0x8c, 0x63, 0x59, 0x7c, 0x04, 0x3b, 0x57, 0x57,
	0xbb, 0xaa, 0xba, 0x06, 0x58, 0xaa, 0x92, 0xcd, 0x92, 0x94, 0x91, 0x1b, 0x9a, 0x69, 0x52, 0x6b,
	0x52, 0xa3, 0x95, 0x92, 0x46, 0xe2, 0x5e, 0xc1, 0x94, 0x73, 0x3f, 0x8e, 0x77, 0xa0, 0x7f, 0x97,
	0xe8, 0xe7, 0xa9, 0x49, 0x8c, 0xd5, 0x9c, 0x5e, 0x2d, 0x69, 0x13, 0xbf, 0x45, 0x80, 0xd5, 0xa9,
	0x5e, 0xc9, 0x4c, 0x13, 0x32, 0x68, 0xe7, 0x7f, 0x0b, 0x43, 0x2c, 0x3a, 0x8a, 0x86, 0x5d, 0xbe,
	0x85, 0xb8, 0x0f, 0x2d, 0x9b, 0xcd, 0x65, 0x46, 0xec, 0x9f, 0x23, 0x1a, 0xbc, 0x40, 0x78, 0x08,
	0xe0, 0x6c, 0x52, 0xd2, 0x5a, 0x64, 0x0f, 0xac, 0xee, 0xb9, 0xca, 0x04, 0x07, 0xd0, 0x59, 0x88,
	0x4c, 0xe8, 0x47, 0x9a, 0xb3, 0x86, 0x67, 0x4b, 0x9c, 0x6b, 0x2e, 0x12, 0xb1, 0x74, 0x4c, 0x33,
	0x68, 0x06, 0x14, 0x1f, 0x43, 0x6f, 0x6a, 0x67, 0x2f, 0xc2, 0xdc, 0xf3, 0xeb, 0x22, 0x30, 0xf6,
	0xa0, 0xee, 0x50, 0x91, 0x2a, 0xff, 0x8c, 0xc7, 0xd0, 0xaf, 0x6c, 0x15, 0x07, 0x38, 0x3b, 0x45,
	0xa9, 0xa0, 0xb5, 0x13, 0xcd, 0x77, 0x3b, 0xbc, 0xc4, 0xb8, 0x0b, 0x4d, 0x52, 0x4a, 0x2a, 0x7f,
	0x41, 0x97, 0x07, 0x70, 0x76, 0x00, 0xff, 0xa7, 0xae, 0x2d, 0x91, 0x52, 0xe8, 0x02, 0x3b, 0xd0,
	0xb8, 0x9a, 0xdc, 0x8c, 0x7b, 0xb5, 0xf3, 0xf7, 0x08, 0xda, 0x97, 0xa1, 0x53, 0x4c, 0x00, 0x38,
	0xa5, 0x24, 0xd6, 0xe4, 0xec, 0xf0, 0x64, 0xf4, 0x6d, 0xd7, 0xa3, 0xcf, 0xb1, 0x07, 0xc3, 0xdf,
	0x17, 0x43, 0xf2, 0xb8, 0x86, 0x4f, 0xee, 0x20, 0x1f, 0x61, 0xb2, 0xc8, 0x9f, 0xe6, 0xd6, 0x92,
	0x25, 0xfc, 0x49, 0xe0, 0xcb, 0x93, 0x0e, 0x4e, 0xff, 0xb0, 0xb9, 0xf5, 0x9a, 0xb5, 0x3c, 0x77,
	0xf1, 0x11, 0x00, 0x00, 0xff, 0xff, 0x82, 0x1e, 0x48, 0x57, 0x4e, 0x02, 0x00, 0x00,
}
