// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawlertowebserver.proto

package crawlerwebserverproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Status of the Crawler.
type ServiceStatus int32

const (
	ServiceStatus_DONE ServiceStatus = 0
)

var ServiceStatus_name = map[int32]string{
	0: "DONE",
}

var ServiceStatus_value = map[string]int32{
	"DONE": 0,
}

func (x ServiceStatus) String() string {
	return proto.EnumName(ServiceStatus_name, int32(x))
}

func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{0}
}

type STATUS_OF_THE_ENTIRE_SYSTEM int32

const (
	STATUS_OF_THE_ENTIRE_SYSTEM_undefined       STATUS_OF_THE_ENTIRE_SYSTEM = 0
	STATUS_OF_THE_ENTIRE_SYSTEM_done            STATUS_OF_THE_ENTIRE_SYSTEM = 1
	STATUS_OF_THE_ENTIRE_SYSTEM_running         STATUS_OF_THE_ENTIRE_SYSTEM = 2
	STATUS_OF_THE_ENTIRE_SYSTEM_unexpected_exit STATUS_OF_THE_ENTIRE_SYSTEM = 3
)

var STATUS_OF_THE_ENTIRE_SYSTEM_name = map[int32]string{
	0: "undefined",
	1: "done",
	2: "running",
	3: "unexpected_exit",
}

var STATUS_OF_THE_ENTIRE_SYSTEM_value = map[string]int32{
	"undefined":       0,
	"done":            1,
	"running":         2,
	"unexpected_exit": 3,
}

func (x STATUS_OF_THE_ENTIRE_SYSTEM) String() string {
	return proto.EnumName(STATUS_OF_THE_ENTIRE_SYSTEM_name, int32(x))
}

func (STATUS_OF_THE_ENTIRE_SYSTEM) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{1}
}

type HasFinishedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasFinishedRequest) Reset()         { *m = HasFinishedRequest{} }
func (m *HasFinishedRequest) String() string { return proto.CompactTextString(m) }
func (*HasFinishedRequest) ProtoMessage()    {}
func (*HasFinishedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{0}
}

func (m *HasFinishedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasFinishedRequest.Unmarshal(m, b)
}
func (m *HasFinishedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasFinishedRequest.Marshal(b, m, deterministic)
}
func (m *HasFinishedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasFinishedRequest.Merge(m, src)
}
func (m *HasFinishedRequest) XXX_Size() int {
	return xxx_messageInfo_HasFinishedRequest.Size(m)
}
func (m *HasFinishedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasFinishedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasFinishedRequest proto.InternalMessageInfo

type HasFinishedResponse struct {
	State                STATUS_OF_THE_ENTIRE_SYSTEM `protobuf:"varint,1,opt,name=state,proto3,enum=crawlerwebserverproto.STATUS_OF_THE_ENTIRE_SYSTEM" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *HasFinishedResponse) Reset()         { *m = HasFinishedResponse{} }
func (m *HasFinishedResponse) String() string { return proto.CompactTextString(m) }
func (*HasFinishedResponse) ProtoMessage()    {}
func (*HasFinishedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{1}
}

func (m *HasFinishedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasFinishedResponse.Unmarshal(m, b)
}
func (m *HasFinishedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasFinishedResponse.Marshal(b, m, deterministic)
}
func (m *HasFinishedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasFinishedResponse.Merge(m, src)
}
func (m *HasFinishedResponse) XXX_Size() int {
	return xxx_messageInfo_HasFinishedResponse.Size(m)
}
func (m *HasFinishedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasFinishedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasFinishedResponse proto.InternalMessageInfo

func (m *HasFinishedResponse) GetState() STATUS_OF_THE_ENTIRE_SYSTEM {
	if m != nil {
		return m.State
	}
	return STATUS_OF_THE_ENTIRE_SYSTEM_undefined
}

//
//TaskStatusRequest will represent a request for the current status of the tasks.
type TaskStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusRequest) Reset()         { *m = TaskStatusRequest{} }
func (m *TaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*TaskStatusRequest) ProtoMessage()    {}
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{2}
}

func (m *TaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusRequest.Unmarshal(m, b)
}
func (m *TaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *TaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusRequest.Merge(m, src)
}
func (m *TaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_TaskStatusRequest.Size(m)
}
func (m *TaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusRequest proto.InternalMessageInfo

//
//TaskStatusResponse will represent a response for a TaskStatusRequest.
type TaskStatusResponse struct {
	Website              string   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Undone               uint64   `protobuf:"varint,2,opt,name=undone,proto3" json:"undone,omitempty"`
	Processing           uint64   `protobuf:"varint,3,opt,name=processing,proto3" json:"processing,omitempty"`
	Finished             uint64   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Failed               uint64   `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatusResponse) Reset()         { *m = TaskStatusResponse{} }
func (m *TaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatusResponse) ProtoMessage()    {}
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{3}
}

func (m *TaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatusResponse.Unmarshal(m, b)
}
func (m *TaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *TaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatusResponse.Merge(m, src)
}
func (m *TaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatusResponse.Size(m)
}
func (m *TaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatusResponse proto.InternalMessageInfo

func (m *TaskStatusResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *TaskStatusResponse) GetUndone() uint64 {
	if m != nil {
		return m.Undone
	}
	return 0
}

func (m *TaskStatusResponse) GetProcessing() uint64 {
	if m != nil {
		return m.Processing
	}
	return 0
}

func (m *TaskStatusResponse) GetFinished() uint64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func (m *TaskStatusResponse) GetFailed() uint64 {
	if m != nil {
		return m.Failed
	}
	return 0
}

//
//SubmitURLRequest will submit a URL.
type SubmitURLRequest struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLRequest) Reset()         { *m = SubmitURLRequest{} }
func (m *SubmitURLRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitURLRequest) ProtoMessage()    {}
func (*SubmitURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{4}
}

func (m *SubmitURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLRequest.Unmarshal(m, b)
}
func (m *SubmitURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLRequest.Marshal(b, m, deterministic)
}
func (m *SubmitURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLRequest.Merge(m, src)
}
func (m *SubmitURLRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitURLRequest.Size(m)
}
func (m *SubmitURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLRequest proto.InternalMessageInfo

func (m *SubmitURLRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

//
//SubmitURLResponse will answer a SubmitURLRequest with a bool to indecate the status of the request.
type SubmitURLResponse struct {
	Recieved             bool     `protobuf:"varint,1,opt,name=recieved,proto3" json:"recieved,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitURLResponse) Reset()         { *m = SubmitURLResponse{} }
func (m *SubmitURLResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitURLResponse) ProtoMessage()    {}
func (*SubmitURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f1f999edb578de9, []int{5}
}

func (m *SubmitURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitURLResponse.Unmarshal(m, b)
}
func (m *SubmitURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitURLResponse.Marshal(b, m, deterministic)
}
func (m *SubmitURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitURLResponse.Merge(m, src)
}
func (m *SubmitURLResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitURLResponse.Size(m)
}
func (m *SubmitURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitURLResponse proto.InternalMessageInfo

func (m *SubmitURLResponse) GetRecieved() bool {
	if m != nil {
		return m.Recieved
	}
	return false
}

func (m *SubmitURLResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("crawlerwebserverproto.ServiceStatus", ServiceStatus_name, ServiceStatus_value)
	proto.RegisterEnum("crawlerwebserverproto.STATUS_OF_THE_ENTIRE_SYSTEM", STATUS_OF_THE_ENTIRE_SYSTEM_name, STATUS_OF_THE_ENTIRE_SYSTEM_value)
	proto.RegisterType((*HasFinishedRequest)(nil), "crawlerwebserverproto.HasFinishedRequest")
	proto.RegisterType((*HasFinishedResponse)(nil), "crawlerwebserverproto.HasFinishedResponse")
	proto.RegisterType((*TaskStatusRequest)(nil), "crawlerwebserverproto.TaskStatusRequest")
	proto.RegisterType((*TaskStatusResponse)(nil), "crawlerwebserverproto.TaskStatusResponse")
	proto.RegisterType((*SubmitURLRequest)(nil), "crawlerwebserverproto.SubmitURLRequest")
	proto.RegisterType((*SubmitURLResponse)(nil), "crawlerwebserverproto.SubmitURLResponse")
}

func init() {
	proto.RegisterFile("crawlertowebserver.proto", fileDescriptor_8f1f999edb578de9)
}

var fileDescriptor_8f1f999edb578de9 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0xb5, 0x49, 0xa6, 0x2a, 0xb8, 0x93, 0x82, 0x4c, 0x90, 0x10, 0xb2, 0x90, 0x28, 0x79,
	0xc8, 0x43, 0xf8, 0x02, 0x04, 0xae, 0x82, 0x04, 0x8d, 0x58, 0xbb, 0x12, 0x3c, 0x59, 0x8e, 0x33,
	0x81, 0x85, 0xb2, 0x0e, 0x7b, 0x49, 0xfb, 0x2d, 0x7c, 0x0d, 0x9f, 0xc6, 0xda, 0xde, 0x44, 0x86,
	0x12, 0xda, 0x37, 0x9f, 0x99, 0xd9, 0x73, 0xf6, 0x9c, 0x59, 0x83, 0x9f, 0xc9, 0xf4, 0xea, 0x92,
	0xa4, 0xce, 0xaf, 0x68, 0xa1, 0x48, 0x6e, 0x48, 0x4e, 0xd6, 0x32, 0xd7, 0x39, 0x3e, 0x70, 0x9d,
	0x5d, 0xbd, 0x2c, 0x07, 0x27, 0x80, 0xb3, 0x54, 0x9d, 0x71, 0xc1, 0xd5, 0x17, 0x5a, 0x32, 0xfa,
	0x61, 0x48, 0xe9, 0x20, 0x81, 0xe1, 0x1f, 0x55, 0xb5, 0xce, 0x85, 0x22, 0x9c, 0x41, 0x57, 0xe9,
	0x54, 0x93, 0xdf, 0x7c, 0xda, 0x3c, 0xbd, 0x37, 0x9d, 0x4e, 0xfe, 0xc9, 0x39, 0x89, 0xe2, 0x57,
	0xf1, 0x45, 0x94, 0xcc, 0xcf, 0x92, 0x78, 0x16, 0x26, 0xe1, 0x79, 0xfc, 0x96, 0x85, 0x49, 0xf4,
	0x29, 0x8a, 0xc3, 0xf7, 0xac, 0x22, 0x08, 0x86, 0x70, 0x1c, 0xa7, 0xea, 0x5b, 0x64, 0x81, 0x51,
	0x5b, 0xd5, 0x9f, 0x4d, 0xc0, 0x7a, 0xd5, 0xa9, 0xfa, 0xd0, 0x2b, 0x04, 0xb8, 0xd3, 0x1d, 0xb0,
	0x2d, 0xc4, 0x87, 0x70, 0x60, 0xc4, 0x32, 0x17, 0xe4, 0xb7, 0x6c, 0xa3, 0xc3, 0x1c, 0xc2, 0x27,
	0x00, 0xf6, 0x26, 0x19, 0x29, 0xc5, 0xc5, 0x67, 0xbf, 0x5d, 0xf6, 0x6a, 0x15, 0x1c, 0x41, 0x7f,
	0xe5, 0xbc, 0xf9, 0x9d, 0xb2, 0xbb, 0xc3, 0x05, 0xe7, 0x2a, 0xe5, 0x97, 0xb6, 0xd3, 0xad, 0x38,
	0x2b, 0x14, 0x3c, 0x03, 0x2f, 0x32, 0x8b, 0xef, 0x5c, 0x5f, 0xb0, 0x77, 0xee, 0xc2, 0xe8, 0x41,
	0xdb, 0x22, 0x77, 0xab, 0xe2, 0x33, 0x08, 0xe1, 0xb8, 0x36, 0xe5, 0x0c, 0x58, 0x39, 0x49, 0x19,
	0xa7, 0x8d, 0x25, 0x2d, 0x66, 0xfb, 0x6c, 0x87, 0xf1, 0x04, 0xba, 0x24, 0x65, 0x2e, 0x4b, 0x07,
	0x03, 0x56, 0x81, 0xf1, 0x23, 0x38, 0x8a, 0x6c, 0xa0, 0x3c, 0xa3, 0x2a, 0x0b, 0xec, 0x43, 0xe7,
	0xcd, 0xfc, 0x3c, 0xf4, 0x1a, 0xe3, 0x8f, 0xf0, 0xf8, 0x3f, 0xf9, 0xe2, 0x11, 0x0c, 0x6c, 0x08,
	0x64, 0xed, 0xd0, 0xd2, 0x6b, 0x14, 0xe7, 0x8a, 0x44, 0xbc, 0x26, 0x1e, 0x42, 0x4f, 0x1a, 0x21,
	0xac, 0x7d, 0xaf, 0x85, 0x43, 0xb8, 0x6f, 0x04, 0x5d, 0xaf, 0x29, 0xd3, 0xb4, 0x4c, 0xe8, 0x9a,
	0x6b, 0xaf, 0x3d, 0xfd, 0xd5, 0x82, 0xde, 0xeb, 0x6a, 0xa1, 0x98, 0x02, 0x30, 0xca, 0x88, 0x6f,
	0xc8, 0x1a, 0xc1, 0xe7, 0xfb, 0x16, 0xfd, 0x57, 0x20, 0xa3, 0xd3, 0xdb, 0x07, 0xab, 0x4c, 0x82,
	0x06, 0x7e, 0xb5, 0x51, 0x95, 0xe6, 0xe6, 0xab, 0x62, 0xe9, 0x1f, 0x0c, 0x19, 0xc2, 0x7d, 0x04,
	0x37, 0x1e, 0xcb, 0xe8, 0xc5, 0x1d, 0x26, 0x77, 0x5a, 0x2b, 0x38, 0xac, 0xbd, 0x67, 0xdc, 0x77,
	0xf6, 0xe6, 0x9f, 0x30, 0x1a, 0xdf, 0x65, 0x74, 0xab, 0xb3, 0x38, 0x28, 0x9b, 0x2f, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0xc7, 0x5a, 0x93, 0x87, 0x03, 0x00, 0x00,
}
