# Dockerfile webserver

FROM golang:1.14 as build
WORKDIR /app 
ADD . . 
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o webserver . 

FROM alpine:latest
COPY --from=build /app/webserver /app/
COPY views /app/views
WORKDIR /app 
EXPOSE 8081
ENTRYPOINT [ "./webserver" ] 