FROM golang:1.14-alpine as build

WORKDIR /go/src/app
ADD . /go/src/app
RUN apk add --no-cache ca-certificates cmake make g++ openssl-dev git curl pkgconfig
RUN apk add libressl-dev
RUN git clone -b 1.7 https://github.com/neo4j-drivers/seabolt.git /seabolt
WORKDIR /seabolt/build
RUN cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_LIBDIR=lib .. && cmake --build . --target install
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
WORKDIR /go/src/app/analyser
EXPOSE 8200
CMD ["go", "run", "main.go"]
